version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - dupl
    - dupword
    - durationcheck
    - errorlint
    - errchkjson
    - exhaustive
    - forcetypeassert
    # - gochecknoglobals
    - goconst
    - gocritic
    # - goerr113
    - gosec
    - ireturn
    - loggercheck
    - mirror
    - misspell
    # - musttag
    - nakedret
    # - nestif
    - nilerr
    #- noctx
    - nonamedreturns
    - predeclared
    - reassign
    - revive
    - sqlclosecheck
    # - tagliatelle
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    # - varnamelen
    - whitespace

formatters:
  enable:
    - gofmt
