# .github/workflows/release.yaml
name: Release

on:
  release:
    types: [created]
  workflow_dispatch: {}

env:
  PLATFORMS: linux/amd64, linux/arm64

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get git tag
        uses: little-core-labs/get-git-tag@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ghcr.io/crumbhole/vault-init:${{ env.GIT_TAG_NAME }}
